---
language: python
python: "2.7"
dist: trusty
sudo: required

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local
  - source $(find /opt/ros -mindepth 2 -maxdepth 2 -name setup.bash)
  - which roscore

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
